### ISSUE TITLE
1.6.0 Fails to connect to non-local redis

### ISSUE THREAD

**Issue by egeland** [coralproject/talk#594] opened 2017-05-17 06:45 UTC
### Expected behaviour
Webapp homepage should load, including the `/api/v1/graph/ql` call.

### Actual behaviour
Running 1.6.0 in kubernetes, the site fails with a spinner, rather than loading the comment stream.
The `ql` call fails with a `400` error.

### Steps to reproduce behaviour
Run 1.5.x in kubernetes, then change the `deployment` to have 1.6.0.
Try to reload the page - spinner/`400` error.

**Comment by kgardnr** [comment] 2017-05-17 19:49
Thank you for reporting this @egeland! We will take a look.

**Comment by kgardnr** [comment] 2017-06-01 15:03
Hi @egeland, could you try updating to 1.7.0 and see if you're still experiencing this issue?

**Comment by egeland** [comment] 2017-06-02 04:58
I just tried `1.8.0` since it's the latest, and still getting the `400` and thus the infinite spinner...

**Comment by wyattjoh** [comment] 2017-06-08 14:51
Are you sure @egeland that there isn't an issue with the k8s setup? We've deployed Talk to various environments where mongodb/redis were located elsewhere and/or linked with docker links + docker compose.

If you set `DEBUG=talk:redis`, what do you see in the output from the server?

**Comment by wyattjoh** [comment] 2017-06-08 14:56
Our redis connection is also very simple, using the `redis` package in a very standard and well supported way: https://github.com/coralproject/talk/blob/master/services/redis.js#L35

**Comment by egeland** [comment] 2017-06-09 02:30
I'm off work today, so I'll try it again next week, with the debug setting.

The weird thing is that the older version, using the same redis config, works fine. It just fails when I change to use docker image 1.6.0 or above..

**Comment by wyattjoh** [comment] 2017-06-16 13:31
I've attempted, but cannot reproduce the error you are encountering. We have many developers and production environments using non-local redis installs.

Closing for now.

**Closed as completed by wyattjoh** 2017-06-16 13:31 UTC
Labels: can't reproduce
