### ISSUE TITLE
Configure Stream tab doesn't appear when logging into stream

### ISSUE THREAD

**Issue by jde** [coralproject/talk#241] opened 2017-01-17 15:51 UTC
### Expected behavior

If you are logged in as an admin, you should always have the Configure Stream tab available.

### Actual behavior

Admins need to log in, then refresh the stream to see the tab.

![stream-settings-tab-needs-refresh](https://cloud.githubusercontent.com/assets/259957/22027769/e1099874-dca2-11e6-845f-1f26a714393c.gif)

### Steps to reproduce behavior

* Log in as an admin
* Note that there's no tab
* Refresh, see the tab appear

**Comment by okbel** [comment] 2017-01-17 15:56
I can't reproduce this. This is how I see it:

![out](https://cloud.githubusercontent.com/assets/1401559/22027965/4a1e727e-dcb4-11e6-8283-b275e45f026d.gif)

**Comment by okbel** [comment] 2017-01-17 15:58
The only thing different I see is that you are login in with Facebook. Odd.

**Comment by kgardnr** [comment] 2017-01-17 21:28
This is working again! Closing :)

**Closed as completed by kgardnr** 2017-01-17 21:28 UTC
