### ISSUE TITLE
Error Viewing User's Comments When Role Is Assigned To Staff

### ISSUE THREAD

**Issue by jonwinton** [coralproject/talk#1263] opened 2018-01-10 14:59 UTC
### Expected behavior
Can view a user's comments whose role has been marked as `STAFF`.

### Actual behavior
Cannot view comments for user and the following error appears in the console (screenshot also attached).

```
Uncaught (in promise) Error: GraphQL error: Expected a value of type "USER_ROLES" but received: STAFF
GraphQL error: Expected a value of type "USER_ROLES" but received: STAFF
```

![screen shot 2018-01-10 at 9 51 05 am](https://user-images.githubusercontent.com/4906712/34778680-0715dc22-f5ec-11e7-99c0-596a1ee14aa1.png)

### Steps to reproduce behavior
- Mark a user role as `Staff` in the admin tool

### Additional Details
The test user was created with a plugin, so the provider is not `local`, but the this is the user object as it exists in Mongo. Hopefully some other property isn't malformed!

```
{
	"_id" : ObjectId("5a37eaa1e4cd9fc18b540d6c"),
	"id" : "3372",
	"updated_at" : ISODate("2018-01-02T18:46:04.570Z"),
	"username" : "kmaloni",
	"lowercaseUsername" : "kmaloni",
	"roles" : [
		"STAFF"
	],
	"profiles" : [
		{
			"id" : "kelly@nymag.com",
			"provider" : "nymag"
		}
	],
	"__v" : 1,
	"created_at" : ISODate("2006-09-14T04:22:00Z"),
	"tokens" : [ ],
	"status" : "ACTIVE",
	"canEditName" : false,
	"suspension" : {
		"until" : null
	},
	"settings" : {
		"bio" : ""
	},
	"ignoresUsers" : [ ],
	"tags" : [ ],
	"metadata" : {
		"trust" : {
			"comment" : {
				"karma" : -5
			}
		}
	}
}
```

**Comment by jonwinton** [comment] 2018-01-10 15:03
Does a user need a `local` profile to have a newsroom role assigned?

**Comment by kgardnr** [comment] 2018-01-11 21:30
Hey @jonwinton, I'm going to leave this bug as pending. We can't reproduce it on our end with 3.9.0. 

With that said though, we are doing a huge refactor of user roles and statuses for 4.0.0, so if it is an issue, it will definitely be fixed in our upcoming release :)

Thank you for alerting us to this though!

**Comment by kgardnr** [comment] 2018-01-18 17:44
Can you test this with 4.0.0 and let us know if you're still seeing this issue @jonwinton? Thank you!

**Comment by jonwinton** [comment] 2018-01-18 18:32
👍 will do

**Comment by kgardnr** [comment] 2018-02-23 20:09
Hey @jonwinton are you still experiencing this issue?

**Closed as completed** 2018-04-25 19:34 UTC
Labels: bug, can't reproduce
