### ISSUE TITLE
Comment Text lost after login via createComment-signIn

### ISSUE THREAD

**Issue by frisi** [coralproject/talk#3425] opened 2021-02-03 14:35 UTC
By default anonymous users see the comment field with a "sign in and join the conversation" button below

![grafik](https://user-images.githubusercontent.com/1120517/106761213-e0c0db00-6634-11eb-9b8c-0f15d00baa97.png)

## usecase

* Write my comment into the textfield
* Click on "sign in" to submit my comment

## expectation
* button opens popup to register or provide credentials
* after successfull signup/login
  my comment is submitted or the "sign in and join" button is replaced with a "submit" button

## what happens instead

* i can see a submit button BUT
* the comment field gets emptied (my previous work is lost)

![grafik](https://user-images.githubusercontent.com/1120517/106761760-72c8e380-6635-11eb-991c-18fc40f42975.png)

**Comment by wyattjoh** [comment] 2021-02-03 16:29
This seems to be a duplicate of #3418

**Closed as completed by wyattjoh** 2021-02-03 16:29 UTC
